// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: filter.proto

package gcloud

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Gcloud Gfunc contains the configuration necessary to perform transform regular http calls to
// Gcloud Gfunc invocations.
type GfuncPerRoute struct {
	// The name of the function
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// URL is the HTTP Trigger URL assigned to the function in the Google Cloud Functions UI
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GfuncPerRoute) Reset()         { *m = GfuncPerRoute{} }
func (m *GfuncPerRoute) String() string { return proto.CompactTextString(m) }
func (*GfuncPerRoute) ProtoMessage()    {}
func (*GfuncPerRoute) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f5303cab7a20d6f, []int{0}
}
func (m *GfuncPerRoute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GfuncPerRoute.Unmarshal(m, b)
}
func (m *GfuncPerRoute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GfuncPerRoute.Marshal(b, m, deterministic)
}
func (m *GfuncPerRoute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GfuncPerRoute.Merge(m, src)
}
func (m *GfuncPerRoute) XXX_Size() int {
	return xxx_messageInfo_GfuncPerRoute.Size(m)
}
func (m *GfuncPerRoute) XXX_DiscardUnknown() {
	xxx_messageInfo_GfuncPerRoute.DiscardUnknown(m)
}

var xxx_messageInfo_GfuncPerRoute proto.InternalMessageInfo

func (m *GfuncPerRoute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GfuncPerRoute) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type GfuncProtocolExtension struct {
	// The Google Cloud Platform project id where the functions are contained
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// The region for this cluster
	Region string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	// The access_key for Gcloud this cluster
	AccessKey string `protobuf:"bytes,3,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	// The json_key for Gcloud this cluster
	JsonKey              string   `protobuf:"bytes,4,opt,name=json_key,json=jsonKey,proto3" json:"json_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GfuncProtocolExtension) Reset()         { *m = GfuncProtocolExtension{} }
func (m *GfuncProtocolExtension) String() string { return proto.CompactTextString(m) }
func (*GfuncProtocolExtension) ProtoMessage()    {}
func (*GfuncProtocolExtension) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f5303cab7a20d6f, []int{1}
}
func (m *GfuncProtocolExtension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GfuncProtocolExtension.Unmarshal(m, b)
}
func (m *GfuncProtocolExtension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GfuncProtocolExtension.Marshal(b, m, deterministic)
}
func (m *GfuncProtocolExtension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GfuncProtocolExtension.Merge(m, src)
}
func (m *GfuncProtocolExtension) XXX_Size() int {
	return xxx_messageInfo_GfuncProtocolExtension.Size(m)
}
func (m *GfuncProtocolExtension) XXX_DiscardUnknown() {
	xxx_messageInfo_GfuncProtocolExtension.DiscardUnknown(m)
}

var xxx_messageInfo_GfuncProtocolExtension proto.InternalMessageInfo

func (m *GfuncProtocolExtension) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *GfuncProtocolExtension) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *GfuncProtocolExtension) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *GfuncProtocolExtension) GetJsonKey() string {
	if m != nil {
		return m.JsonKey
	}
	return ""
}

func init() {
	proto.RegisterType((*GfuncPerRoute)(nil), "envoy.config.filter.http.gcloud.v2.GfuncPerRoute")
	proto.RegisterType((*GfuncProtocolExtension)(nil), "envoy.config.filter.http.gcloud.v2.GfuncProtocolExtension")
}

func init() { proto.RegisterFile("filter.proto", fileDescriptor_1f5303cab7a20d6f) }

var fileDescriptor_1f5303cab7a20d6f = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xbd, 0x4e, 0xf3, 0x30,
	0x14, 0x86, 0x95, 0x36, 0x6a, 0xbf, 0x5a, 0x1f, 0x8b, 0x07, 0x08, 0x30, 0x50, 0x65, 0x40, 0x2c,
	0xd8, 0x12, 0x2c, 0x88, 0x31, 0x12, 0xaa, 0x50, 0x17, 0xd4, 0x91, 0xa5, 0x4a, 0x9d, 0x13, 0xd7,
	0xad, 0xeb, 0x13, 0xf9, 0x27, 0x22, 0x17, 0xc5, 0x0d, 0x32, 0xa1, 0xfc, 0x30, 0x34, 0x9b, 0xfd,
	0x3e, 0xc7, 0x8f, 0x8f, 0x5e, 0xf2, 0xbf, 0x54, 0xda, 0x83, 0x65, 0x95, 0x45, 0x8f, 0x34, 0x05,
	0x53, 0x63, 0xc3, 0x04, 0x9a, 0x52, 0x49, 0x36, 0xa0, 0xbd, 0xf7, 0x15, 0x93, 0x42, 0x63, 0x28,
	0x58, 0xfd, 0x74, 0x73, 0x55, 0xe7, 0x5a, 0x15, 0xb9, 0x07, 0xfe, 0x77, 0xe8, 0x1f, 0xa7, 0x2b,
	0x72, 0xb1, 0x2a, 0x83, 0x11, 0x1f, 0x60, 0x37, 0x18, 0x3c, 0xd0, 0x5b, 0x12, 0x9b, 0xfc, 0x04,
	0x49, 0xb4, 0x8c, 0x1e, 0x16, 0xd9, 0xfc, 0x27, 0x8b, 0xed, 0x64, 0x19, 0x6d, 0xba, 0x90, 0x5e,
	0x93, 0x69, 0xb0, 0x3a, 0x99, 0x9c, 0xb3, 0x36, 0x4b, 0xbf, 0x23, 0x72, 0xd9, 0x9b, 0x5a, 0xaf,
	0x40, 0xfd, 0xf6, 0xe5, 0xc1, 0x38, 0x85, 0x86, 0xde, 0x13, 0x52, 0x59, 0x3c, 0x80, 0xf0, 0x5b,
	0x55, 0x8c, 0xc5, 0x8b, 0x01, 0xbd, 0x17, 0xf4, 0x8e, 0xcc, 0x2c, 0x48, 0x85, 0x66, 0xfc, 0xc1,
	0x10, 0xb7, 0xa2, 0x5c, 0x08, 0x70, 0x6e, 0x7b, 0x84, 0x26, 0x99, 0x8e, 0x44, 0x3d, 0x5a, 0x43,
	0x43, 0x53, 0xf2, 0xef, 0xe0, 0xd0, 0x74, 0x53, 0xf1, 0xf9, 0xd4, 0xbc, 0x05, 0x6b, 0x68, 0xb2,
	0xd7, 0xcf, 0x17, 0xa9, 0xfc, 0x3e, 0xec, 0x98, 0xc0, 0x13, 0x77, 0xa8, 0xf1, 0x51, 0x21, 0x97,
	0x1a, 0x91, 0x0f, 0x1b, 0xb9, 0xe1, 0x76, 0x94, 0xbc, 0xd2, 0x41, 0x2a, 0xe3, 0x78, 0x5f, 0xe8,
	0x6e, 0xd6, 0x75, 0xf7, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x9e, 0xc7, 0x04, 0x88, 0x01,
	0x00, 0x00,
}
