// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: filter.proto

package gcloud

import (
	fmt "fmt"
	math "math"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Gcloud Gfunc contains the configuration necessary to perform transform regular http calls to
// Gcloud Gfunc invocations.
type GfuncPerRoute struct {
	// The name of the function
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The qualifier of the function (defaults to $LATEST if not specified)
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Invocation type - async or regular.
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GfuncPerRoute) Reset()         { *m = GfuncPerRoute{} }
func (m *GfuncPerRoute) String() string { return proto.CompactTextString(m) }
func (*GfuncPerRoute) ProtoMessage()    {}
func (*GfuncPerRoute) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f5303cab7a20d6f, []int{0}
}
func (m *GfuncPerRoute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GfuncPerRoute.Unmarshal(m, b)
}
func (m *GfuncPerRoute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GfuncPerRoute.Marshal(b, m, deterministic)
}
func (m *GfuncPerRoute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GfuncPerRoute.Merge(m, src)
}
func (m *GfuncPerRoute) XXX_Size() int {
	return xxx_messageInfo_GfuncPerRoute.Size(m)
}
func (m *GfuncPerRoute) XXX_DiscardUnknown() {
	xxx_messageInfo_GfuncPerRoute.DiscardUnknown(m)
}

var xxx_messageInfo_GfuncPerRoute proto.InternalMessageInfo

func (m *GfuncPerRoute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GfuncPerRoute) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type GfuncProtocolExtension struct {
        // The Google Cloud Platform project id where the functions are contained
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,proto3" json:"project_id,omitempty"`
	// The region for this cluster
	Region string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	// The access_key for Gcloud this cluster
	AccessKey string `protobuf:"bytes,3,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	// The json_key for Gcloud this cluster
	JsonKey string   `protobuf:"bytes,4,opt,name=json_key,json=jsonKey,proto3" json:"json_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GfuncProtocolExtension) Reset()         { *m = GfuncProtocolExtension{} }
func (m *GfuncProtocolExtension) String() string { return proto.CompactTextString(m) }
func (*GfuncProtocolExtension) ProtoMessage()    {}
func (*GfuncProtocolExtension) Descriptor() ([]byte, []int) {
	return fileDescriptorSpec, []int{1}
}
func (m *GfuncProtocolExtension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GfuncProtocolExtension.Unmarshal(m, b)
}
func (m *GfuncProtocolExtension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GfuncProtocolExtension.Marshal(b, m, deterministic)
}
func (m *GfuncProtocolExtension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GfuncProtocolExtension.Merge(m, src)
}
func (m *GfuncProtocolExtension) XXX_Size() int {
	return xxx_messageInfo_GfuncProtocolExtension.Size(m)
}
func (m *GfuncProtocolExtension) XXX_DiscardUnknown() {
	xxx_messageInfo_GfuncProtocolExtension.DiscardUnknown(m)
}

var xxx_messageInfo_GfuncProtocolExtension proto.InternalMessageInfo

func (m *GfuncProtocolExtension) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *GfuncProtocolExtension) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *GfuncProtocolExtension) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *GfuncProtocolExtension) GetJsonKey() string {
	if m != nil {
		return m.JsonKey
	}
	return ""
}

func init() {
	proto.RegisterType((*GfuncPerRoute)(nil), "envoy.config.filter.http.gcloud.v2.GfuncPerRoute")
	proto.RegisterType((*GfuncProtocolExtension)(nil), "envoy.config.filter.http.gcloud.v2.GfuncProtocolExtension")
}

func init() { proto.RegisterFile("filter.proto", fileDescriptorSpec) }

var fileDescriptorSpec = []byte{
        // 197 bytes of a gzipped FileDescriptorProto
        0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x8e, 0xcd, 0x4a, 0xc5, 0x30,
        0x10, 0x85, 0xa9, 0x42, 0xa1, 0x43, 0x17, 0x12, 0x44, 0x8a, 0xa0, 0x94, 0xae, 0x44, 0x30, 0x51,
        0x7c, 0x03, 0x41, 0xc1, 0xad, 0xe2, 0xc6, 0x8d, 0xb4, 0x69, 0x18, 0xa3, 0x69, 0x66, 0xc8, 0x8f,
        0xcf, 0xe4, 0x73, 0xdd, 0x27, 0xb9, 0x34, 0xed, 0xee, 0xcc, 0x9c, 0xc3, 0xc7, 0x07, 0x10, 0xd9,
        0x68, 0xc9, 0x81, 0x12, 0x09, 0x81, 0x8e, 0x48, 0x8e, 0x6c, 0x25, 0x12, 0xa1, 0x33, 0xf2, 0xef,
        0xe1, 0xf2, 0x1c, 0x09, 0xa9, 0xd4, 0x6a, 0x4d, 0xdb, 0x72, 0x78, 0x86, 0xf6, 0x83, 0x63, 0x0a,
        0x66, 0x5c, 0xde, 0xd9, 0x68, 0x71, 0x01, 0x75, 0x30, 0x68, 0xc9, 0x77, 0x55, 0x5f, 0xdd, 0x34,
        0x6f, 0xfb, 0x25, 0xae, 0x00, 0x38, 0xd0, 0x8f, 0xd1, 0xe9, 0xcb, 0xce, 0xdd, 0x49, 0xe9, 0x9a,
        0xfd, 0xf3, 0x3a, 0x0f, 0x3d, 0xb4, 0x2f, 0xd9, 0xeb, 0x64, 0xc9, 0x17, 0xcc, 0x19, 0x9c, 0xe6,
        0xe0, 0x76, 0xc6, 0x1a, 0x9f, 0xee, 0xff, 0x0f, 0xd7, 0xd5, 0xe7, 0x2d, 0xda, 0xf4, 0x9d, 0x27,
        0xa9, 0x69, 0x51, 0x91, 0x1c, 0xdd, 0x59, 0x52, 0xab, 0xab, 0xe2, 0x5f, 0x54, 0xec, 0x32, 0x5a,
        0x1f, 0xd5, 0xe6, 0x3c, 0xd5, 0xc5, 0xf0, 0xf1, 0x18, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x64, 0x39,
        0x67, 0xd9, 0x00, 0x00, 0x00,
}

